-- File: vhdl_out/top.vhd
-- Generated by MyHDL 0.11.51
-- Date:    Thu Dec  4 06:50:03 2025 UTC


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity top is
    port (
        clk: in std_logic;
        reset: in std_logic;
        start: in std_logic;
        done: out std_logic;
        matrix_A_in: in unsigned(511 downto 0);
        matrix_L_out: out unsigned(511 downto 0);
        matrix_U_out: out unsigned(511 downto 0)
    );
end entity top;


architecture MyHDL of top is



signal lu_inst_accumulator: signed (40 downto 0);
signal lu_inst_div_dividend: signed (32 downto 0);
signal lu_inst_div_divisor: signed (32 downto 0);
signal lu_inst_div_done: std_logic;
signal lu_inst_div_quotient: signed (32 downto 0);
signal lu_inst_div_start: std_logic;
signal lu_inst_i: unsigned(2 downto 0);
signal lu_inst_j: unsigned(2 downto 0);
signal lu_inst_k: unsigned(2 downto 0);
signal lu_inst_m: unsigned(2 downto 0);
signal lu_inst_state: unsigned(3 downto 0);
signal lu_inst_divider_done_reg: std_logic;
signal lu_inst_divider_mul1: signed (128 downto 0);
signal lu_inst_divider_mul2: signed (128 downto 0);
signal lu_inst_divider_reg_d_abs: unsigned(47 downto 0);
signal lu_inst_divider_reg_d_norm: unsigned(47 downto 0);
signal lu_inst_divider_reg_dividend: signed (48 downto 0);
signal lu_inst_divider_reg_divisor: signed (48 downto 0);
signal lu_inst_divider_reg_index: unsigned(7 downto 0);
signal lu_inst_divider_reg_seed: unsigned(39 downto 0);
signal lu_inst_divider_reg_shift: signed (6 downto 0);
signal lu_inst_divider_rom_addr: unsigned(7 downto 0);
signal lu_inst_divider_rom_out: unsigned(24 downto 0);
signal lu_inst_divider_state: unsigned(3 downto 0);
type t_array_A_list is array(0 to 16-1) of signed (31 downto 0);
signal A_list: t_array_A_list;
type t_array_L_list is array(0 to 16-1) of signed (31 downto 0);
signal L_list: t_array_L_list;
type t_array_U_list is array(0 to 16-1) of signed (31 downto 0);
signal U_list: t_array_U_list;

begin




top_lu_inst_fsm: process (clk) is
    variable row: integer;
    variable col: integer;
    variable prod: integer;
begin
    if rising_edge(clk) then
        if (reset = '1') then
            lu_inst_i <= to_unsigned(0, 3);
            U_list(0) <= to_signed(0, 32);
            U_list(1) <= to_signed(0, 32);
            U_list(2) <= to_signed(0, 32);
            U_list(3) <= to_signed(0, 32);
            U_list(4) <= to_signed(0, 32);
            U_list(5) <= to_signed(0, 32);
            U_list(6) <= to_signed(0, 32);
            U_list(7) <= to_signed(0, 32);
            U_list(8) <= to_signed(0, 32);
            U_list(9) <= to_signed(0, 32);
            U_list(10) <= to_signed(0, 32);
            U_list(11) <= to_signed(0, 32);
            U_list(12) <= to_signed(0, 32);
            U_list(13) <= to_signed(0, 32);
            U_list(14) <= to_signed(0, 32);
            U_list(15) <= to_signed(0, 32);
            lu_inst_k <= to_unsigned(0, 3);
            lu_inst_accumulator <= to_signed(0, 41);
            lu_inst_div_start <= '0';
            lu_inst_div_dividend <= to_signed(0, 33);
            done <= '0';
            L_list(0) <= to_signed(0, 32);
            L_list(1) <= to_signed(0, 32);
            L_list(2) <= to_signed(0, 32);
            L_list(3) <= to_signed(0, 32);
            L_list(4) <= to_signed(0, 32);
            L_list(5) <= to_signed(0, 32);
            L_list(6) <= to_signed(0, 32);
            L_list(7) <= to_signed(0, 32);
            L_list(8) <= to_signed(0, 32);
            L_list(9) <= to_signed(0, 32);
            L_list(10) <= to_signed(0, 32);
            L_list(11) <= to_signed(0, 32);
            L_list(12) <= to_signed(0, 32);
            L_list(13) <= to_signed(0, 32);
            L_list(14) <= to_signed(0, 32);
            L_list(15) <= to_signed(0, 32);
            lu_inst_m <= to_unsigned(0, 3);
            lu_inst_j <= to_unsigned(0, 3);
            lu_inst_state <= to_unsigned(0, 4);
            lu_inst_div_divisor <= to_signed(0, 33);
        else
            lu_inst_div_start <= '0';
            case lu_inst_state is
                when "0000" =>
                    done <= '0';
                    if bool(start) then
                        lu_inst_state <= to_unsigned(1, 4);
                    end if;
                when "0001" =>
                    for idx in 0 to (4 * 4)-1 loop
                        row := (idx / 4);
                        col := (idx mod 4);
                        if (row = col) then
                            L_list(idx) <= to_signed(shift_left(1, 24), 32);
                        else
                            L_list(idx) <= to_signed(0, 32);
                        end if;
                        U_list(idx) <= to_signed(0, 32);
                    end loop;
                    lu_inst_k <= to_unsigned(0, 3);
                    lu_inst_j <= to_unsigned(0, 3);
                    lu_inst_state <= to_unsigned(2, 4);
                when "0010" =>
                    if (to_integer(lu_inst_j) >= 4) then
                        lu_inst_i <= to_unsigned(to_integer(lu_inst_k) + 1, 3);
                        lu_inst_state <= to_unsigned(4, 4);
                    elsif (to_integer(lu_inst_j) < to_integer(lu_inst_k)) then
                        lu_inst_j <= to_unsigned(to_integer(lu_inst_j) + 1, 3);
                    else
                        lu_inst_accumulator <= to_signed(to_integer(A_list(((to_integer(lu_inst_k) * 4) + to_integer(lu_inst_j)))), 41);
                        lu_inst_m <= to_unsigned(0, 3);
                        lu_inst_state <= to_unsigned(3, 4);
                    end if;
                when "0011" =>
                    if (to_integer(lu_inst_m) < to_integer(lu_inst_k)) then
                        prod := shift_right((to_integer(L_list(((to_integer(lu_inst_k) * 4) + to_integer(lu_inst_m)))) * to_integer(U_list(((to_integer(lu_inst_m) * 4) + to_integer(lu_inst_j))))), 24);
                        lu_inst_accumulator <= to_signed(to_integer(lu_inst_accumulator) - prod, 41);
                        lu_inst_m <= to_unsigned(to_integer(lu_inst_m) + 1, 3);
                    else
                        U_list(((to_integer(lu_inst_k) * 4) + to_integer(lu_inst_j))) <= to_signed(to_integer(lu_inst_accumulator), 32);
                        lu_inst_j <= to_unsigned(to_integer(lu_inst_j) + 1, 3);
                        lu_inst_state <= to_unsigned(2, 4);
                    end if;
                when "0100" =>
                    if (to_integer(lu_inst_i) >= 4) then
                        lu_inst_state <= to_unsigned(8, 4);
                    else
                        lu_inst_accumulator <= to_signed(to_integer(A_list(((to_integer(lu_inst_i) * 4) + to_integer(lu_inst_k)))), 41);
                        lu_inst_m <= to_unsigned(0, 3);
                        lu_inst_state <= to_unsigned(5, 4);
                    end if;
                when "0101" =>
                    if (to_integer(lu_inst_m) < to_integer(lu_inst_k)) then
                        prod := shift_right((to_integer(L_list(((to_integer(lu_inst_i) * 4) + to_integer(lu_inst_m)))) * to_integer(U_list(((to_integer(lu_inst_m) * 4) + to_integer(lu_inst_k))))), 24);
                        lu_inst_accumulator <= to_signed(to_integer(lu_inst_accumulator) - prod, 41);
                        lu_inst_m <= to_unsigned(to_integer(lu_inst_m) + 1, 3);
                    else
                        lu_inst_div_dividend <= to_signed(to_integer(lu_inst_accumulator), 33);
                        lu_inst_div_divisor <= to_signed(to_integer(U_list(((to_integer(lu_inst_k) * 4) + to_integer(lu_inst_k)))), 33);
                        lu_inst_div_start <= '1';
                        lu_inst_state <= to_unsigned(7, 4);
                    end if;
                when "0111" =>
                    if bool(lu_inst_div_done) then
                        L_list(((to_integer(lu_inst_i) * 4) + to_integer(lu_inst_k))) <= to_signed(to_integer(lu_inst_div_quotient), 32);
                        lu_inst_i <= to_unsigned(to_integer(lu_inst_i) + 1, 3);
                        lu_inst_state <= to_unsigned(4, 4);
                    end if;
                when "1000" =>
                    lu_inst_k <= to_unsigned(to_integer(lu_inst_k) + 1, 3);
                    if ((to_integer(lu_inst_k) + 1) >= 4) then
                        lu_inst_state <= to_unsigned(9, 4);
                    else
                        lu_inst_j <= to_unsigned(0, 3);
                        lu_inst_state <= to_unsigned(2, 4);
                    end if;
                when "1001" =>
                    done <= '1';
                    if (not bool(start)) then
                        lu_inst_state <= to_unsigned(0, 4);
                    end if;
                when others =>
                    lu_inst_state <= to_unsigned(0, 4);
            end case;
        end if;
    end if;
end process top_lu_inst_fsm;

top_lu_inst_divider_fsm: process (clk) is
    variable d: integer;
    variable d_abs: integer;
    variable msb_pos_val: integer;
    variable b: integer;
    variable shift: integer;
    variable d_norm_val: integer;
    variable index_val: integer;
    variable frac_mask: integer;
    variable seed_val: integer;
    variable d_norm: integer;
    variable prod: integer;
    variable prod_q: integer;
    variable two_q: integer;
    variable two_minus: integer;
    variable xnext: integer;
    variable recip_q: integer;
    variable recip_actual_val: integer;
begin
    if rising_edge(clk) then
        if (reset = '1') then
            lu_inst_divider_reg_d_norm <= to_unsigned(0, 48);
            lu_inst_divider_reg_index <= to_unsigned(0, 8);
            lu_inst_divider_mul1 <= to_signed(0, 129);
            lu_inst_divider_rom_addr <= to_unsigned(0, 8);
            lu_inst_divider_reg_d_abs <= to_unsigned(0, 48);
            lu_inst_divider_reg_seed <= to_unsigned(0, 40);
            lu_inst_div_done <= '0';
            lu_inst_divider_reg_dividend <= to_signed(0, 49);
            lu_inst_divider_reg_shift <= to_signed(0, 7);
            lu_inst_divider_reg_divisor <= to_signed(0, 49);
            lu_inst_divider_state <= to_unsigned(0, 4);
            lu_inst_divider_mul2 <= to_signed(0, 129);
            lu_inst_div_quotient <= to_signed(0, 33);
            lu_inst_divider_done_reg <= '0';
        else
            lu_inst_divider_done_reg <= '0';
            case lu_inst_divider_state is
                when "0000" =>
                    lu_inst_div_done <= '0';
                    if bool(lu_inst_div_start) then
                        lu_inst_divider_reg_dividend <= to_signed(to_integer(lu_inst_div_dividend), 49);
                        lu_inst_divider_reg_divisor <= to_signed(to_integer(lu_inst_div_divisor), 49);
                        lu_inst_divider_state <= to_unsigned(1, 4);
                    else
                        lu_inst_divider_state <= to_unsigned(0, 4);
                    end if;
                when "0001" =>
                    d := to_integer(lu_inst_divider_reg_divisor);
                    if (d = 0) then
                        lu_inst_div_quotient <= to_signed(0, 33);
                        lu_inst_divider_done_reg <= '1';
                        lu_inst_divider_state <= to_unsigned(7, 4);
                    else
                        if (d >= 0) then
                            lu_inst_divider_reg_d_abs <= to_unsigned(d, 48);
                        else
                            lu_inst_divider_reg_d_abs <= to_unsigned((-d), 48);
                        end if;
                        lu_inst_divider_state <= to_unsigned(2, 4);
                    end if;
                when "0010" =>
                    d_abs := to_integer(lu_inst_divider_reg_d_abs);
                    msb_pos_val := 0;
                    for bi in 0 to (32 + 16)-1 loop
                        b := (((32 + 16) - 1) - bi);
                        if ((d_abs and shift_left(1, b)) /= 0) then
                            msb_pos_val := b;
                            exit;
                        end if;
                    end loop;
                    shift := (msb_pos_val - 24);
                    lu_inst_divider_reg_shift <= to_signed(shift, 7);
                    lu_inst_divider_state <= to_unsigned(3, 4);
                when "0011" =>
                    d_abs := to_integer(lu_inst_divider_reg_d_abs);
                    shift := to_integer(lu_inst_divider_reg_shift);
                    d_norm_val := 0;
                    index_val := 0;
                    if (shift >= 0) then
                        d_norm_val := shift_right(d_abs, shift);
                    else
                        d_norm_val := shift_left(d_abs, (-shift));
                    end if;
                    lu_inst_divider_reg_d_norm <= to_unsigned(d_norm_val, 48);
                    if (24 >= 8) then
                        frac_mask := (shift_left(1, 24) - 1);
                        index_val := shift_right((d_norm_val and frac_mask), (24 - 8));
                    else
                        index_val := (shift_left(d_norm_val, (8 - 24)) and 255);
                    end if;
                    lu_inst_divider_reg_index <= to_unsigned(index_val, 8);
                    lu_inst_divider_rom_addr <= to_unsigned(index_val, 8);
                    lu_inst_divider_state <= to_unsigned(4, 4);
                when "0100" =>
                    seed_val := to_integer(lu_inst_divider_rom_out);
                    lu_inst_divider_reg_seed <= to_unsigned(seed_val, 40);
                    d_norm := to_integer(lu_inst_divider_reg_d_norm);
                    prod := (d_norm * seed_val);
                    lu_inst_divider_mul1 <= to_signed(prod, 129);
                    lu_inst_divider_state <= to_unsigned(5, 4);
                when "0101" =>
                    prod_q := shift_right(to_integer(lu_inst_divider_mul1), 24);
                    two_q := shift_left(2, 24);
                    two_minus := (two_q - prod_q);
                    xnext := shift_right((to_integer(lu_inst_divider_reg_seed) * two_minus), 24);
                    lu_inst_divider_mul2 <= to_signed(xnext, 129);
                    lu_inst_divider_state <= to_unsigned(6, 4);
                when "0110" =>
                    recip_q := to_integer(lu_inst_divider_mul2);
                    shift := to_integer(lu_inst_divider_reg_shift);
                    recip_actual_val := 0;
                    if (shift > 0) then
                        recip_actual_val := shift_right(recip_q, shift);
                    elsif (shift < 0) then
                        recip_actual_val := shift_left(recip_q, (-shift));
                    else
                        recip_actual_val := recip_q;
                    end if;
                    if (to_integer(lu_inst_divider_reg_divisor) < 0) then
                        recip_actual_val := (-recip_actual_val);
                    end if;
                    prod_q := shift_right((to_integer(lu_inst_divider_reg_dividend) * recip_actual_val), 24);
                    lu_inst_div_quotient <= to_signed(prod_q, 33);
                    lu_inst_divider_done_reg <= '1';
                    lu_inst_divider_state <= to_unsigned(7, 4);
                when "0111" =>
                    lu_inst_divider_done_reg <= '1';
                    if (not bool(lu_inst_div_start)) then
                        lu_inst_divider_state <= to_unsigned(0, 4);
                    end if;
                when others =>
                    lu_inst_divider_state <= to_unsigned(0, 4);
            end case;
            lu_inst_div_done <= lu_inst_divider_done_reg;
        end if;
    end if;
end process top_lu_inst_divider_fsm;

top_lu_inst_divider_rom_lookup: process (lu_inst_divider_rom_addr) is
    variable idx: integer;
begin
    idx := to_integer(lu_inst_divider_rom_addr);
    if ((idx >= 0) and (idx < 256)) then
        case idx is
            when 0 => lu_inst_divider_rom_out <= "0111111111000000001000000";
            when 1 => lu_inst_divider_rom_out <= "0111111101000001000111101";
            when 2 => lu_inst_divider_rom_out <= "0111111011000011000110001";
            when 3 => lu_inst_divider_rom_out <= "0111111001000110000010110";
            when 4 => lu_inst_divider_rom_out <= "0111110111001001111100110";
            when 5 => lu_inst_divider_rom_out <= "0111110101001110110011101";
            when 6 => lu_inst_divider_rom_out <= "0111110011010100100110100";
            when 7 => lu_inst_divider_rom_out <= "0111110001011011010100110";
            when 8 => lu_inst_divider_rom_out <= "0111101111100010111101110";
            when 9 => lu_inst_divider_rom_out <= "0111101101101011100000101";
            when 10 => lu_inst_divider_rom_out <= "0111101011110100111101000";
            when 11 => lu_inst_divider_rom_out <= "0111101001111111010010001";
            when 12 => lu_inst_divider_rom_out <= "0111101000001010011111010";
            when 13 => lu_inst_divider_rom_out <= "0111100110010110100011111";
            when 14 => lu_inst_divider_rom_out <= "0111100100100011011111011";
            when 15 => lu_inst_divider_rom_out <= "0111100010110001010001001";
            when 16 => lu_inst_divider_rom_out <= "0111100000111111111000100";
            when 17 => lu_inst_divider_rom_out <= "0111011111001111010101000";
            when 18 => lu_inst_divider_rom_out <= "0111011101011111100101111";
            when 19 => lu_inst_divider_rom_out <= "0111011011110000101010110";
            when 20 => lu_inst_divider_rom_out <= "0111011010000010100011000";
            when 21 => lu_inst_divider_rom_out <= "0111011000010101001110000";
            when 22 => lu_inst_divider_rom_out <= "0111010110101000101011010";
            when 23 => lu_inst_divider_rom_out <= "0111010100111100111010001";
            when 24 => lu_inst_divider_rom_out <= "0111010011010001111010010";
            when 25 => lu_inst_divider_rom_out <= "0111010001100111101011001";
            when 26 => lu_inst_divider_rom_out <= "0111001111111110001100000";
            when 27 => lu_inst_divider_rom_out <= "0111001110010101011100100";
            when 28 => lu_inst_divider_rom_out <= "0111001100101101011100010";
            when 29 => lu_inst_divider_rom_out <= "0111001011000110001010100";
            when 30 => lu_inst_divider_rom_out <= "0111001001011111100111000";
            when 31 => lu_inst_divider_rom_out <= "0111000111111001110001001";
            when 32 => lu_inst_divider_rom_out <= "0111000110010100101000011";
            when 33 => lu_inst_divider_rom_out <= "0111000100110000001100011";
            when 34 => lu_inst_divider_rom_out <= "0111000011001100011100101";
            when 35 => lu_inst_divider_rom_out <= "0111000001101001011000110";
            when 36 => lu_inst_divider_rom_out <= "0111000000000111000000001";
            when 37 => lu_inst_divider_rom_out <= "0110111110100101010010011";
            when 38 => lu_inst_divider_rom_out <= "0110111101000100001111010";
            when 39 => lu_inst_divider_rom_out <= "0110111011100011110110000";
            when 40 => lu_inst_divider_rom_out <= "0110111010000100000110100";
            when 41 => lu_inst_divider_rom_out <= "0110111000100101000000001";
            when 42 => lu_inst_divider_rom_out <= "0110110111000110100010100";
            when 43 => lu_inst_divider_rom_out <= "0110110101101000101101010";
            when 44 => lu_inst_divider_rom_out <= "0110110100001011100000000";
            when 45 => lu_inst_divider_rom_out <= "0110110010101110111010011";
            when 46 => lu_inst_divider_rom_out <= "0110110001010010111011111";
            when 47 => lu_inst_divider_rom_out <= "0110101111110111100100001";
            when 48 => lu_inst_divider_rom_out <= "0110101110011100110010111";
            when 49 => lu_inst_divider_rom_out <= "0110101101000010100111101";
            when 50 => lu_inst_divider_rom_out <= "0110101011101001000010000";
            when 51 => lu_inst_divider_rom_out <= "0110101010010000000001101";
            when 52 => lu_inst_divider_rom_out <= "0110101000110111100110010";
            when 53 => lu_inst_divider_rom_out <= "0110100111011111101111100";
            when 54 => lu_inst_divider_rom_out <= "0110100110001000011100111";
            when 55 => lu_inst_divider_rom_out <= "0110100100110001101110001";
            when 56 => lu_inst_divider_rom_out <= "0110100011011011100010111";
            when 57 => lu_inst_divider_rom_out <= "0110100010000101111010111";
            when 58 => lu_inst_divider_rom_out <= "0110100000110000110101110";
            when 59 => lu_inst_divider_rom_out <= "0110011111011100010011001";
            when 60 => lu_inst_divider_rom_out <= "0110011110001000010010101";
            when 61 => lu_inst_divider_rom_out <= "0110011100110100110100000";
            when 62 => lu_inst_divider_rom_out <= "0110011011100001110111000";
            when 63 => lu_inst_divider_rom_out <= "0110011010001111011011001";
            when 64 => lu_inst_divider_rom_out <= "0110011000111101100000010";
            when 65 => lu_inst_divider_rom_out <= "0110010111101100000110000";
            when 66 => lu_inst_divider_rom_out <= "0110010110011011001100000";
            when 67 => lu_inst_divider_rom_out <= "0110010101001010110010000";
            when 68 => lu_inst_divider_rom_out <= "0110010011111010110111111";
            when 69 => lu_inst_divider_rom_out <= "0110010010101011011101000";
            when 70 => lu_inst_divider_rom_out <= "0110010001011100100001011";
            when 71 => lu_inst_divider_rom_out <= "0110010000001110000100100";
            when 72 => lu_inst_divider_rom_out <= "0110001111000000000110010";
            when 73 => lu_inst_divider_rom_out <= "0110001101110010100110010";
            when 74 => lu_inst_divider_rom_out <= "0110001100100101100100010";
            when 75 => lu_inst_divider_rom_out <= "0110001011011001000000001";
            when 76 => lu_inst_divider_rom_out <= "0110001010001100111001011";
            when 77 => lu_inst_divider_rom_out <= "0110001001000001001111111";
            when 78 => lu_inst_divider_rom_out <= "0110000111110110000011010";
            when 79 => lu_inst_divider_rom_out <= "0110000110101011010011011";
            when 80 => lu_inst_divider_rom_out <= "0110000101100000111111111";
            when 81 => lu_inst_divider_rom_out <= "0110000100010111001000101";
            when 82 => lu_inst_divider_rom_out <= "0110000011001101101101010";
            when 83 => lu_inst_divider_rom_out <= "0110000010000100101101101";
            when 84 => lu_inst_divider_rom_out <= "0110000000111100001001011";
            when 85 => lu_inst_divider_rom_out <= "0101111111110100000000011";
            when 86 => lu_inst_divider_rom_out <= "0101111110101100010010010";
            when 87 => lu_inst_divider_rom_out <= "0101111101100100111111000";
            when 88 => lu_inst_divider_rom_out <= "0101111100011110000110001";
            when 89 => lu_inst_divider_rom_out <= "0101111011010111100111100";
            when 90 => lu_inst_divider_rom_out <= "0101111010010001100011000";
            when 91 => lu_inst_divider_rom_out <= "0101111001001011111000010";
            when 92 => lu_inst_divider_rom_out <= "0101111000000110100111001";
            when 93 => lu_inst_divider_rom_out <= "0101110111000001101111011";
            when 94 => lu_inst_divider_rom_out <= "0101110101111101010000110";
            when 95 => lu_inst_divider_rom_out <= "0101110100111001001011000";
            when 96 => lu_inst_divider_rom_out <= "0101110011110101011110000";
            when 97 => lu_inst_divider_rom_out <= "0101110010110010001001101";
            when 98 => lu_inst_divider_rom_out <= "0101110001101111001101100";
            when 99 => lu_inst_divider_rom_out <= "0101110000101100101001011";
            when 100 => lu_inst_divider_rom_out <= "0101101111101010011101010";
            when 101 => lu_inst_divider_rom_out <= "0101101110101000101000111";
            when 102 => lu_inst_divider_rom_out <= "0101101101100111001011111";
            when 103 => lu_inst_divider_rom_out <= "0101101100100110000110010";
            when 104 => lu_inst_divider_rom_out <= "0101101011100101010111110";
            when 105 => lu_inst_divider_rom_out <= "0101101010100101000000001";
            when 106 => lu_inst_divider_rom_out <= "0101101001100100111111010";
            when 107 => lu_inst_divider_rom_out <= "0101101000100101010100111";
            when 108 => lu_inst_divider_rom_out <= "0101100111100110000000111";
            when 109 => lu_inst_divider_rom_out <= "0101100110100111000011001";
            when 110 => lu_inst_divider_rom_out <= "0101100101101000011011010";
            when 111 => lu_inst_divider_rom_out <= "0101100100101010001001010";
            when 112 => lu_inst_divider_rom_out <= "0101100011101100001100111";
            when 113 => lu_inst_divider_rom_out <= "0101100010101110100101111";
            when 114 => lu_inst_divider_rom_out <= "0101100001110001010100010";
            when 115 => lu_inst_divider_rom_out <= "0101100000110100010111110";
            when 116 => lu_inst_divider_rom_out <= "0101011111110111110000010";
            when 117 => lu_inst_divider_rom_out <= "0101011110111011011101011";
            when 118 => lu_inst_divider_rom_out <= "0101011101111111011111010";
            when 119 => lu_inst_divider_rom_out <= "0101011101000011110101011";
            when 120 => lu_inst_divider_rom_out <= "0101011100001000100000000";
            when 121 => lu_inst_divider_rom_out <= "0101011011001101011110101";
            when 122 => lu_inst_divider_rom_out <= "0101011010010010110001010";
            when 123 => lu_inst_divider_rom_out <= "0101011001011000010111101";
            when 124 => lu_inst_divider_rom_out <= "0101011000011110010001101";
            when 125 => lu_inst_divider_rom_out <= "0101010111100100011111010";
            when 126 => lu_inst_divider_rom_out <= "0101010110101011000000001";
            when 127 => lu_inst_divider_rom_out <= "0101010101110001110100001";
            when 128 => lu_inst_divider_rom_out <= "0101010100111000111011010";
            when 129 => lu_inst_divider_rom_out <= "0101010100000000010101010";
            when 130 => lu_inst_divider_rom_out <= "0101010011001000000010000";
            when 131 => lu_inst_divider_rom_out <= "0101010010010000000001011";
            when 132 => lu_inst_divider_rom_out <= "0101010001011000010011001";
            when 133 => lu_inst_divider_rom_out <= "0101010000100000110111010";
            when 134 => lu_inst_divider_rom_out <= "0101001111101001101101100";
            when 135 => lu_inst_divider_rom_out <= "0101001110110010110101110";
            when 136 => lu_inst_divider_rom_out <= "0101001101111100010000000";
            when 137 => lu_inst_divider_rom_out <= "0101001101000101111011111";
            when 138 => lu_inst_divider_rom_out <= "0101001100001111111001100";
            when 139 => lu_inst_divider_rom_out <= "0101001011011010001000101";
            when 140 => lu_inst_divider_rom_out <= "0101001010100100101001000";
            when 141 => lu_inst_divider_rom_out <= "0101001001101111011010101";
            when 142 => lu_inst_divider_rom_out <= "0101001000111010011101011";
            when 143 => lu_inst_divider_rom_out <= "0101001000000101110001001";
            when 144 => lu_inst_divider_rom_out <= "0101000111010001010101101";
            when 145 => lu_inst_divider_rom_out <= "0101000110011101001010111";
            when 146 => lu_inst_divider_rom_out <= "0101000101101001010000110";
            when 147 => lu_inst_divider_rom_out <= "0101000100110101100111001";
            when 148 => lu_inst_divider_rom_out <= "0101000100000010001101110";
            when 149 => lu_inst_divider_rom_out <= "0101000011001111000100101";
            when 150 => lu_inst_divider_rom_out <= "0101000010011100001011101";
            when 151 => lu_inst_divider_rom_out <= "0101000001101001100010101";
            when 152 => lu_inst_divider_rom_out <= "0101000000110111001001100";
            when 153 => lu_inst_divider_rom_out <= "0101000000000101000000001";
            when 154 => lu_inst_divider_rom_out <= "0100111111010011000110011";
            when 155 => lu_inst_divider_rom_out <= "0100111110100001011100001";
            when 156 => lu_inst_divider_rom_out <= "0100111101110000000001010";
            when 157 => lu_inst_divider_rom_out <= "0100111100111110110101110";
            when 158 => lu_inst_divider_rom_out <= "0100111100001101111001011";
            when 159 => lu_inst_divider_rom_out <= "0100111011011101001100001";
            when 160 => lu_inst_divider_rom_out <= "0100111010101100101101110";
            when 161 => lu_inst_divider_rom_out <= "0100111001111100011110011";
            when 162 => lu_inst_divider_rom_out <= "0100111001001100011101101";
            when 163 => lu_inst_divider_rom_out <= "0100111000011100101011101";
            when 164 => lu_inst_divider_rom_out <= "0100110111101101001000001";
            when 165 => lu_inst_divider_rom_out <= "0100110110111101110011001";
            when 166 => lu_inst_divider_rom_out <= "0100110110001110101100011";
            when 167 => lu_inst_divider_rom_out <= "0100110101011111110011111";
            when 168 => lu_inst_divider_rom_out <= "0100110100110001001001101";
            when 169 => lu_inst_divider_rom_out <= "0100110100000010101101010";
            when 170 => lu_inst_divider_rom_out <= "0100110011010100011110111";
            when 171 => lu_inst_divider_rom_out <= "0100110010100110011110011";
            when 172 => lu_inst_divider_rom_out <= "0100110001111000101011101";
            when 173 => lu_inst_divider_rom_out <= "0100110001001011000110100";
            when 174 => lu_inst_divider_rom_out <= "0100110000011101101110111";
            when 175 => lu_inst_divider_rom_out <= "0100101111110000100100110";
            when 176 => lu_inst_divider_rom_out <= "0100101111000011101000000";
            when 177 => lu_inst_divider_rom_out <= "0100101110010110111000100";
            when 178 => lu_inst_divider_rom_out <= "0100101101101010010110010";
            when 179 => lu_inst_divider_rom_out <= "0100101100111110000001000";
            when 180 => lu_inst_divider_rom_out <= "0100101100010001111000111";
            when 181 => lu_inst_divider_rom_out <= "0100101011100101111101100";
            when 182 => lu_inst_divider_rom_out <= "0100101010111010001111000";
            when 183 => lu_inst_divider_rom_out <= "0100101010001110101101010";
            when 184 => lu_inst_divider_rom_out <= "0100101001100011011000010";
            when 185 => lu_inst_divider_rom_out <= "0100101000111000001111101";
            when 186 => lu_inst_divider_rom_out <= "0100101000001101010011101";
            when 187 => lu_inst_divider_rom_out <= "0100100111100010100011111";
            when 188 => lu_inst_divider_rom_out <= "0100100110111000000000101";
            when 189 => lu_inst_divider_rom_out <= "0100100110001101101001100";
            when 190 => lu_inst_divider_rom_out <= "0100100101100011011110100";
            when 191 => lu_inst_divider_rom_out <= "0100100100111001011111100";
            when 192 => lu_inst_divider_rom_out <= "0100100100001111101100101";
            when 193 => lu_inst_divider_rom_out <= "0100100011100110000101100";
            when 194 => lu_inst_divider_rom_out <= "0100100010111100101010011";
            when 195 => lu_inst_divider_rom_out <= "0100100010010011011010111";
            when 196 => lu_inst_divider_rom_out <= "0100100001101010010111000";
            when 197 => lu_inst_divider_rom_out <= "0100100001000001011110111";
            when 198 => lu_inst_divider_rom_out <= "0100100000011000110010001";
            when 199 => lu_inst_divider_rom_out <= "0100011111110000010000111";
            when 200 => lu_inst_divider_rom_out <= "0100011111000111111011000";
            when 201 => lu_inst_divider_rom_out <= "0100011110011111110000011";
            when 202 => lu_inst_divider_rom_out <= "0100011101110111110000111";
            when 203 => lu_inst_divider_rom_out <= "0100011101001111111100101";
            when 204 => lu_inst_divider_rom_out <= "0100011100101000010011100";
            when 205 => lu_inst_divider_rom_out <= "0100011100000000110101010";
            when 206 => lu_inst_divider_rom_out <= "0100011011011001100010000";
            when 207 => lu_inst_divider_rom_out <= "0100011010110010011001100";
            when 208 => lu_inst_divider_rom_out <= "0100011010001011011011111";
            when 209 => lu_inst_divider_rom_out <= "0100011001100100101001000";
            when 210 => lu_inst_divider_rom_out <= "0100011000111110000000101";
            when 211 => lu_inst_divider_rom_out <= "0100011000010111100011000";
            when 212 => lu_inst_divider_rom_out <= "0100010111110001001111110";
            when 213 => lu_inst_divider_rom_out <= "0100010111001011000111000";
            when 214 => lu_inst_divider_rom_out <= "0100010110100101001000101";
            when 215 => lu_inst_divider_rom_out <= "0100010101111111010100101";
            when 216 => lu_inst_divider_rom_out <= "0100010101011001101010110";
            when 217 => lu_inst_divider_rom_out <= "0100010100110100001011001";
            when 218 => lu_inst_divider_rom_out <= "0100010100001110110101100";
            when 219 => lu_inst_divider_rom_out <= "0100010011101001101010000";
            when 220 => lu_inst_divider_rom_out <= "0100010011000100101000100";
            when 221 => lu_inst_divider_rom_out <= "0100010010011111110001000";
            when 222 => lu_inst_divider_rom_out <= "0100010001111011000011010";
            when 223 => lu_inst_divider_rom_out <= "0100010001010110011111011";
            when 224 => lu_inst_divider_rom_out <= "0100010000110010000101010";
            when 225 => lu_inst_divider_rom_out <= "0100010000001101110100110";
            when 226 => lu_inst_divider_rom_out <= "0100001111101001101101111";
            when 227 => lu_inst_divider_rom_out <= "0100001111000101110000100";
            when 228 => lu_inst_divider_rom_out <= "0100001110100001111100110";
            when 229 => lu_inst_divider_rom_out <= "0100001101111110010010011";
            when 230 => lu_inst_divider_rom_out <= "0100001101011010110001011";
            when 231 => lu_inst_divider_rom_out <= "0100001100110111011001101";
            when 232 => lu_inst_divider_rom_out <= "0100001100010100001011010";
            when 233 => lu_inst_divider_rom_out <= "0100001011110001000110001";
            when 234 => lu_inst_divider_rom_out <= "0100001011001110001010000";
            when 235 => lu_inst_divider_rom_out <= "0100001010101011010111001";
            when 236 => lu_inst_divider_rom_out <= "0100001010001000101101010";
            when 237 => lu_inst_divider_rom_out <= "0100001001100110001100011";
            when 238 => lu_inst_divider_rom_out <= "0100001001000011110100011";
            when 239 => lu_inst_divider_rom_out <= "0100001000100001100101010";
            when 240 => lu_inst_divider_rom_out <= "0100000111111111011111000";
            when 241 => lu_inst_divider_rom_out <= "0100000111011101100001100";
            when 242 => lu_inst_divider_rom_out <= "0100000110111011101100110";
            when 243 => lu_inst_divider_rom_out <= "0100000110011010000000101";
            when 244 => lu_inst_divider_rom_out <= "0100000101111000011101001";
            when 245 => lu_inst_divider_rom_out <= "0100000101010111000010010";
            when 246 => lu_inst_divider_rom_out <= "0100000100110101101111111";
            when 247 => lu_inst_divider_rom_out <= "0100000100010100100101111";
            when 248 => lu_inst_divider_rom_out <= "0100000011110011100100011";
            when 249 => lu_inst_divider_rom_out <= "0100000011010010101011001";
            when 250 => lu_inst_divider_rom_out <= "0100000010110001111010011";
            when 251 => lu_inst_divider_rom_out <= "0100000010010001010001110";
            when 252 => lu_inst_divider_rom_out <= "0100000001110000110001011";
            when 253 => lu_inst_divider_rom_out <= "0100000001010000011001001";
            when 254 => lu_inst_divider_rom_out <= "0100000000110000001001000";
            when others => lu_inst_divider_rom_out <= "0100000000010000000001000";
        end case;
    else
        case 0 is
            when 0 => lu_inst_divider_rom_out <= "0111111111000000001000000";
            when 1 => lu_inst_divider_rom_out <= "0111111101000001000111101";
            when 2 => lu_inst_divider_rom_out <= "0111111011000011000110001";
            when 3 => lu_inst_divider_rom_out <= "0111111001000110000010110";
            when 4 => lu_inst_divider_rom_out <= "0111110111001001111100110";
            when 5 => lu_inst_divider_rom_out <= "0111110101001110110011101";
            when 6 => lu_inst_divider_rom_out <= "0111110011010100100110100";
            when 7 => lu_inst_divider_rom_out <= "0111110001011011010100110";
            when 8 => lu_inst_divider_rom_out <= "0111101111100010111101110";
            when 9 => lu_inst_divider_rom_out <= "0111101101101011100000101";
            when 10 => lu_inst_divider_rom_out <= "0111101011110100111101000";
            when 11 => lu_inst_divider_rom_out <= "0111101001111111010010001";
            when 12 => lu_inst_divider_rom_out <= "0111101000001010011111010";
            when 13 => lu_inst_divider_rom_out <= "0111100110010110100011111";
            when 14 => lu_inst_divider_rom_out <= "0111100100100011011111011";
            when 15 => lu_inst_divider_rom_out <= "0111100010110001010001001";
            when 16 => lu_inst_divider_rom_out <= "0111100000111111111000100";
            when 17 => lu_inst_divider_rom_out <= "0111011111001111010101000";
            when 18 => lu_inst_divider_rom_out <= "0111011101011111100101111";
            when 19 => lu_inst_divider_rom_out <= "0111011011110000101010110";
            when 20 => lu_inst_divider_rom_out <= "0111011010000010100011000";
            when 21 => lu_inst_divider_rom_out <= "0111011000010101001110000";
            when 22 => lu_inst_divider_rom_out <= "0111010110101000101011010";
            when 23 => lu_inst_divider_rom_out <= "0111010100111100111010001";
            when 24 => lu_inst_divider_rom_out <= "0111010011010001111010010";
            when 25 => lu_inst_divider_rom_out <= "0111010001100111101011001";
            when 26 => lu_inst_divider_rom_out <= "0111001111111110001100000";
            when 27 => lu_inst_divider_rom_out <= "0111001110010101011100100";
            when 28 => lu_inst_divider_rom_out <= "0111001100101101011100010";
            when 29 => lu_inst_divider_rom_out <= "0111001011000110001010100";
            when 30 => lu_inst_divider_rom_out <= "0111001001011111100111000";
            when 31 => lu_inst_divider_rom_out <= "0111000111111001110001001";
            when 32 => lu_inst_divider_rom_out <= "0111000110010100101000011";
            when 33 => lu_inst_divider_rom_out <= "0111000100110000001100011";
            when 34 => lu_inst_divider_rom_out <= "0111000011001100011100101";
            when 35 => lu_inst_divider_rom_out <= "0111000001101001011000110";
            when 36 => lu_inst_divider_rom_out <= "0111000000000111000000001";
            when 37 => lu_inst_divider_rom_out <= "0110111110100101010010011";
            when 38 => lu_inst_divider_rom_out <= "0110111101000100001111010";
            when 39 => lu_inst_divider_rom_out <= "0110111011100011110110000";
            when 40 => lu_inst_divider_rom_out <= "0110111010000100000110100";
            when 41 => lu_inst_divider_rom_out <= "0110111000100101000000001";
            when 42 => lu_inst_divider_rom_out <= "0110110111000110100010100";
            when 43 => lu_inst_divider_rom_out <= "0110110101101000101101010";
            when 44 => lu_inst_divider_rom_out <= "0110110100001011100000000";
            when 45 => lu_inst_divider_rom_out <= "0110110010101110111010011";
            when 46 => lu_inst_divider_rom_out <= "0110110001010010111011111";
            when 47 => lu_inst_divider_rom_out <= "0110101111110111100100001";
            when 48 => lu_inst_divider_rom_out <= "0110101110011100110010111";
            when 49 => lu_inst_divider_rom_out <= "0110101101000010100111101";
            when 50 => lu_inst_divider_rom_out <= "0110101011101001000010000";
            when 51 => lu_inst_divider_rom_out <= "0110101010010000000001101";
            when 52 => lu_inst_divider_rom_out <= "0110101000110111100110010";
            when 53 => lu_inst_divider_rom_out <= "0110100111011111101111100";
            when 54 => lu_inst_divider_rom_out <= "0110100110001000011100111";
            when 55 => lu_inst_divider_rom_out <= "0110100100110001101110001";
            when 56 => lu_inst_divider_rom_out <= "0110100011011011100010111";
            when 57 => lu_inst_divider_rom_out <= "0110100010000101111010111";
            when 58 => lu_inst_divider_rom_out <= "0110100000110000110101110";
            when 59 => lu_inst_divider_rom_out <= "0110011111011100010011001";
            when 60 => lu_inst_divider_rom_out <= "0110011110001000010010101";
            when 61 => lu_inst_divider_rom_out <= "0110011100110100110100000";
            when 62 => lu_inst_divider_rom_out <= "0110011011100001110111000";
            when 63 => lu_inst_divider_rom_out <= "0110011010001111011011001";
            when 64 => lu_inst_divider_rom_out <= "0110011000111101100000010";
            when 65 => lu_inst_divider_rom_out <= "0110010111101100000110000";
            when 66 => lu_inst_divider_rom_out <= "0110010110011011001100000";
            when 67 => lu_inst_divider_rom_out <= "0110010101001010110010000";
            when 68 => lu_inst_divider_rom_out <= "0110010011111010110111111";
            when 69 => lu_inst_divider_rom_out <= "0110010010101011011101000";
            when 70 => lu_inst_divider_rom_out <= "0110010001011100100001011";
            when 71 => lu_inst_divider_rom_out <= "0110010000001110000100100";
            when 72 => lu_inst_divider_rom_out <= "0110001111000000000110010";
            when 73 => lu_inst_divider_rom_out <= "0110001101110010100110010";
            when 74 => lu_inst_divider_rom_out <= "0110001100100101100100010";
            when 75 => lu_inst_divider_rom_out <= "0110001011011001000000001";
            when 76 => lu_inst_divider_rom_out <= "0110001010001100111001011";
            when 77 => lu_inst_divider_rom_out <= "0110001001000001001111111";
            when 78 => lu_inst_divider_rom_out <= "0110000111110110000011010";
            when 79 => lu_inst_divider_rom_out <= "0110000110101011010011011";
            when 80 => lu_inst_divider_rom_out <= "0110000101100000111111111";
            when 81 => lu_inst_divider_rom_out <= "0110000100010111001000101";
            when 82 => lu_inst_divider_rom_out <= "0110000011001101101101010";
            when 83 => lu_inst_divider_rom_out <= "0110000010000100101101101";
            when 84 => lu_inst_divider_rom_out <= "0110000000111100001001011";
            when 85 => lu_inst_divider_rom_out <= "0101111111110100000000011";
            when 86 => lu_inst_divider_rom_out <= "0101111110101100010010010";
            when 87 => lu_inst_divider_rom_out <= "0101111101100100111111000";
            when 88 => lu_inst_divider_rom_out <= "0101111100011110000110001";
            when 89 => lu_inst_divider_rom_out <= "0101111011010111100111100";
            when 90 => lu_inst_divider_rom_out <= "0101111010010001100011000";
            when 91 => lu_inst_divider_rom_out <= "0101111001001011111000010";
            when 92 => lu_inst_divider_rom_out <= "0101111000000110100111001";
            when 93 => lu_inst_divider_rom_out <= "0101110111000001101111011";
            when 94 => lu_inst_divider_rom_out <= "0101110101111101010000110";
            when 95 => lu_inst_divider_rom_out <= "0101110100111001001011000";
            when 96 => lu_inst_divider_rom_out <= "0101110011110101011110000";
            when 97 => lu_inst_divider_rom_out <= "0101110010110010001001101";
            when 98 => lu_inst_divider_rom_out <= "0101110001101111001101100";
            when 99 => lu_inst_divider_rom_out <= "0101110000101100101001011";
            when 100 => lu_inst_divider_rom_out <= "0101101111101010011101010";
            when 101 => lu_inst_divider_rom_out <= "0101101110101000101000111";
            when 102 => lu_inst_divider_rom_out <= "0101101101100111001011111";
            when 103 => lu_inst_divider_rom_out <= "0101101100100110000110010";
            when 104 => lu_inst_divider_rom_out <= "0101101011100101010111110";
            when 105 => lu_inst_divider_rom_out <= "0101101010100101000000001";
            when 106 => lu_inst_divider_rom_out <= "0101101001100100111111010";
            when 107 => lu_inst_divider_rom_out <= "0101101000100101010100111";
            when 108 => lu_inst_divider_rom_out <= "0101100111100110000000111";
            when 109 => lu_inst_divider_rom_out <= "0101100110100111000011001";
            when 110 => lu_inst_divider_rom_out <= "0101100101101000011011010";
            when 111 => lu_inst_divider_rom_out <= "0101100100101010001001010";
            when 112 => lu_inst_divider_rom_out <= "0101100011101100001100111";
            when 113 => lu_inst_divider_rom_out <= "0101100010101110100101111";
            when 114 => lu_inst_divider_rom_out <= "0101100001110001010100010";
            when 115 => lu_inst_divider_rom_out <= "0101100000110100010111110";
            when 116 => lu_inst_divider_rom_out <= "0101011111110111110000010";
            when 117 => lu_inst_divider_rom_out <= "0101011110111011011101011";
            when 118 => lu_inst_divider_rom_out <= "0101011101111111011111010";
            when 119 => lu_inst_divider_rom_out <= "0101011101000011110101011";
            when 120 => lu_inst_divider_rom_out <= "0101011100001000100000000";
            when 121 => lu_inst_divider_rom_out <= "0101011011001101011110101";
            when 122 => lu_inst_divider_rom_out <= "0101011010010010110001010";
            when 123 => lu_inst_divider_rom_out <= "0101011001011000010111101";
            when 124 => lu_inst_divider_rom_out <= "0101011000011110010001101";
            when 125 => lu_inst_divider_rom_out <= "0101010111100100011111010";
            when 126 => lu_inst_divider_rom_out <= "0101010110101011000000001";
            when 127 => lu_inst_divider_rom_out <= "0101010101110001110100001";
            when 128 => lu_inst_divider_rom_out <= "0101010100111000111011010";
            when 129 => lu_inst_divider_rom_out <= "0101010100000000010101010";
            when 130 => lu_inst_divider_rom_out <= "0101010011001000000010000";
            when 131 => lu_inst_divider_rom_out <= "0101010010010000000001011";
            when 132 => lu_inst_divider_rom_out <= "0101010001011000010011001";
            when 133 => lu_inst_divider_rom_out <= "0101010000100000110111010";
            when 134 => lu_inst_divider_rom_out <= "0101001111101001101101100";
            when 135 => lu_inst_divider_rom_out <= "0101001110110010110101110";
            when 136 => lu_inst_divider_rom_out <= "0101001101111100010000000";
            when 137 => lu_inst_divider_rom_out <= "0101001101000101111011111";
            when 138 => lu_inst_divider_rom_out <= "0101001100001111111001100";
            when 139 => lu_inst_divider_rom_out <= "0101001011011010001000101";
            when 140 => lu_inst_divider_rom_out <= "0101001010100100101001000";
            when 141 => lu_inst_divider_rom_out <= "0101001001101111011010101";
            when 142 => lu_inst_divider_rom_out <= "0101001000111010011101011";
            when 143 => lu_inst_divider_rom_out <= "0101001000000101110001001";
            when 144 => lu_inst_divider_rom_out <= "0101000111010001010101101";
            when 145 => lu_inst_divider_rom_out <= "0101000110011101001010111";
            when 146 => lu_inst_divider_rom_out <= "0101000101101001010000110";
            when 147 => lu_inst_divider_rom_out <= "0101000100110101100111001";
            when 148 => lu_inst_divider_rom_out <= "0101000100000010001101110";
            when 149 => lu_inst_divider_rom_out <= "0101000011001111000100101";
            when 150 => lu_inst_divider_rom_out <= "0101000010011100001011101";
            when 151 => lu_inst_divider_rom_out <= "0101000001101001100010101";
            when 152 => lu_inst_divider_rom_out <= "0101000000110111001001100";
            when 153 => lu_inst_divider_rom_out <= "0101000000000101000000001";
            when 154 => lu_inst_divider_rom_out <= "0100111111010011000110011";
            when 155 => lu_inst_divider_rom_out <= "0100111110100001011100001";
            when 156 => lu_inst_divider_rom_out <= "0100111101110000000001010";
            when 157 => lu_inst_divider_rom_out <= "0100111100111110110101110";
            when 158 => lu_inst_divider_rom_out <= "0100111100001101111001011";
            when 159 => lu_inst_divider_rom_out <= "0100111011011101001100001";
            when 160 => lu_inst_divider_rom_out <= "0100111010101100101101110";
            when 161 => lu_inst_divider_rom_out <= "0100111001111100011110011";
            when 162 => lu_inst_divider_rom_out <= "0100111001001100011101101";
            when 163 => lu_inst_divider_rom_out <= "0100111000011100101011101";
            when 164 => lu_inst_divider_rom_out <= "0100110111101101001000001";
            when 165 => lu_inst_divider_rom_out <= "0100110110111101110011001";
            when 166 => lu_inst_divider_rom_out <= "0100110110001110101100011";
            when 167 => lu_inst_divider_rom_out <= "0100110101011111110011111";
            when 168 => lu_inst_divider_rom_out <= "0100110100110001001001101";
            when 169 => lu_inst_divider_rom_out <= "0100110100000010101101010";
            when 170 => lu_inst_divider_rom_out <= "0100110011010100011110111";
            when 171 => lu_inst_divider_rom_out <= "0100110010100110011110011";
            when 172 => lu_inst_divider_rom_out <= "0100110001111000101011101";
            when 173 => lu_inst_divider_rom_out <= "0100110001001011000110100";
            when 174 => lu_inst_divider_rom_out <= "0100110000011101101110111";
            when 175 => lu_inst_divider_rom_out <= "0100101111110000100100110";
            when 176 => lu_inst_divider_rom_out <= "0100101111000011101000000";
            when 177 => lu_inst_divider_rom_out <= "0100101110010110111000100";
            when 178 => lu_inst_divider_rom_out <= "0100101101101010010110010";
            when 179 => lu_inst_divider_rom_out <= "0100101100111110000001000";
            when 180 => lu_inst_divider_rom_out <= "0100101100010001111000111";
            when 181 => lu_inst_divider_rom_out <= "0100101011100101111101100";
            when 182 => lu_inst_divider_rom_out <= "0100101010111010001111000";
            when 183 => lu_inst_divider_rom_out <= "0100101010001110101101010";
            when 184 => lu_inst_divider_rom_out <= "0100101001100011011000010";
            when 185 => lu_inst_divider_rom_out <= "0100101000111000001111101";
            when 186 => lu_inst_divider_rom_out <= "0100101000001101010011101";
            when 187 => lu_inst_divider_rom_out <= "0100100111100010100011111";
            when 188 => lu_inst_divider_rom_out <= "0100100110111000000000101";
            when 189 => lu_inst_divider_rom_out <= "0100100110001101101001100";
            when 190 => lu_inst_divider_rom_out <= "0100100101100011011110100";
            when 191 => lu_inst_divider_rom_out <= "0100100100111001011111100";
            when 192 => lu_inst_divider_rom_out <= "0100100100001111101100101";
            when 193 => lu_inst_divider_rom_out <= "0100100011100110000101100";
            when 194 => lu_inst_divider_rom_out <= "0100100010111100101010011";
            when 195 => lu_inst_divider_rom_out <= "0100100010010011011010111";
            when 196 => lu_inst_divider_rom_out <= "0100100001101010010111000";
            when 197 => lu_inst_divider_rom_out <= "0100100001000001011110111";
            when 198 => lu_inst_divider_rom_out <= "0100100000011000110010001";
            when 199 => lu_inst_divider_rom_out <= "0100011111110000010000111";
            when 200 => lu_inst_divider_rom_out <= "0100011111000111111011000";
            when 201 => lu_inst_divider_rom_out <= "0100011110011111110000011";
            when 202 => lu_inst_divider_rom_out <= "0100011101110111110000111";
            when 203 => lu_inst_divider_rom_out <= "0100011101001111111100101";
            when 204 => lu_inst_divider_rom_out <= "0100011100101000010011100";
            when 205 => lu_inst_divider_rom_out <= "0100011100000000110101010";
            when 206 => lu_inst_divider_rom_out <= "0100011011011001100010000";
            when 207 => lu_inst_divider_rom_out <= "0100011010110010011001100";
            when 208 => lu_inst_divider_rom_out <= "0100011010001011011011111";
            when 209 => lu_inst_divider_rom_out <= "0100011001100100101001000";
            when 210 => lu_inst_divider_rom_out <= "0100011000111110000000101";
            when 211 => lu_inst_divider_rom_out <= "0100011000010111100011000";
            when 212 => lu_inst_divider_rom_out <= "0100010111110001001111110";
            when 213 => lu_inst_divider_rom_out <= "0100010111001011000111000";
            when 214 => lu_inst_divider_rom_out <= "0100010110100101001000101";
            when 215 => lu_inst_divider_rom_out <= "0100010101111111010100101";
            when 216 => lu_inst_divider_rom_out <= "0100010101011001101010110";
            when 217 => lu_inst_divider_rom_out <= "0100010100110100001011001";
            when 218 => lu_inst_divider_rom_out <= "0100010100001110110101100";
            when 219 => lu_inst_divider_rom_out <= "0100010011101001101010000";
            when 220 => lu_inst_divider_rom_out <= "0100010011000100101000100";
            when 221 => lu_inst_divider_rom_out <= "0100010010011111110001000";
            when 222 => lu_inst_divider_rom_out <= "0100010001111011000011010";
            when 223 => lu_inst_divider_rom_out <= "0100010001010110011111011";
            when 224 => lu_inst_divider_rom_out <= "0100010000110010000101010";
            when 225 => lu_inst_divider_rom_out <= "0100010000001101110100110";
            when 226 => lu_inst_divider_rom_out <= "0100001111101001101101111";
            when 227 => lu_inst_divider_rom_out <= "0100001111000101110000100";
            when 228 => lu_inst_divider_rom_out <= "0100001110100001111100110";
            when 229 => lu_inst_divider_rom_out <= "0100001101111110010010011";
            when 230 => lu_inst_divider_rom_out <= "0100001101011010110001011";
            when 231 => lu_inst_divider_rom_out <= "0100001100110111011001101";
            when 232 => lu_inst_divider_rom_out <= "0100001100010100001011010";
            when 233 => lu_inst_divider_rom_out <= "0100001011110001000110001";
            when 234 => lu_inst_divider_rom_out <= "0100001011001110001010000";
            when 235 => lu_inst_divider_rom_out <= "0100001010101011010111001";
            when 236 => lu_inst_divider_rom_out <= "0100001010001000101101010";
            when 237 => lu_inst_divider_rom_out <= "0100001001100110001100011";
            when 238 => lu_inst_divider_rom_out <= "0100001001000011110100011";
            when 239 => lu_inst_divider_rom_out <= "0100001000100001100101010";
            when 240 => lu_inst_divider_rom_out <= "0100000111111111011111000";
            when 241 => lu_inst_divider_rom_out <= "0100000111011101100001100";
            when 242 => lu_inst_divider_rom_out <= "0100000110111011101100110";
            when 243 => lu_inst_divider_rom_out <= "0100000110011010000000101";
            when 244 => lu_inst_divider_rom_out <= "0100000101111000011101001";
            when 245 => lu_inst_divider_rom_out <= "0100000101010111000010010";
            when 246 => lu_inst_divider_rom_out <= "0100000100110101101111111";
            when 247 => lu_inst_divider_rom_out <= "0100000100010100100101111";
            when 248 => lu_inst_divider_rom_out <= "0100000011110011100100011";
            when 249 => lu_inst_divider_rom_out <= "0100000011010010101011001";
            when 250 => lu_inst_divider_rom_out <= "0100000010110001111010011";
            when 251 => lu_inst_divider_rom_out <= "0100000010010001010001110";
            when 252 => lu_inst_divider_rom_out <= "0100000001110000110001011";
            when 253 => lu_inst_divider_rom_out <= "0100000001010000011001001";
            when 254 => lu_inst_divider_rom_out <= "0100000000110000001001000";
            when others => lu_inst_divider_rom_out <= "0100000000010000000001000";
        end case;
    end if;
end process top_lu_inst_divider_rom_lookup;

top_unflatten_inputs: process (matrix_A_in) is
    variable shift: integer;
    variable temp: unsigned(511 downto 0);
begin
    for i in 0 to 16-1 loop
        shift := (i * 32);
        temp := resize(matrix_A_in((shift + 32)-1 downto shift), 512);
        if (temp((32 - 1)) = '1') then
            A_list(i) <= to_signed(to_integer(temp) - shift_left(1, 32), 32);
        else
            A_list(i) <= to_signed(to_integer(temp), 32);
        end if;
    end loop;
end process top_unflatten_inputs;

top_flatten_outputs: process (L_list, U_list) is
    variable outL: integer;
    variable outU: integer;
    variable lv: integer;
    variable uv: integer;
begin
    outL := 0;
    outU := 0;
    for i in 0 to 16-1 loop
        lv := (to_integer(L_list(i)) and 4294967295);
        uv := (to_integer(U_list(i)) and 4294967295);
        outL := (outL or shift_left(lv, (i * 32)));
        outU := (outU or shift_left(uv, (i * 32)));
    end loop;
    matrix_L_out <= outL(512-1 downto 0);
    matrix_U_out <= outU(512-1 downto 0);
end process top_flatten_outputs;

end architecture MyHDL;
